name: scorbord
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  algolia: ^0.1.6+1
  cached_network_image: ^1.1.1
  cloud_firestore: ^0.12.9+1
  curved_navigation_bar: ^0.3.1
  device_info: ^0.4.0+2
  firebase_auth: ^0.14.0+3
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.1.6
  firebase_storage: ^3.0.6
  flutter_custom_clippers: ^1.0.4
  flutter_speed_dial: ^1.2.1
  get_it: ^3.0.1
  http: ^0.12.0+1 
  package_info: ^0.4.0+6
  image_picker: ^0.6.1+3
  intl: ^0.15.7
  intro_views_flutter: '^2.4.0'
  material_design_icons_flutter: ^3.2.4096
  share: ^0.6.0+1
  timeago: ^2.0.10
  url_launcher: ^5.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
